# Pa11y: A tool to check accessibility issue on a webpage
# The config file and sitemap file used by this workflow
# is in the ".github" directory of the repositiory
#
# This workflow is configured to run weekly on 12:30 every Friday
# It can also be run manually from repo's Gihthub page
#----------------------------------------------------------------

name: Pa11y Accessibility Check
on:
  pull_request:
    push:
      branches:
        - main

jobs:
    pa11ly:
        name: Pa11y Test
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up Node.js 22.x
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
            
            - name: Install Pa11y CI
              run: npm install -g pa11y-ci
            
            - name: Run Pa11y CI
              run: |
                pa11y-ci \
                  --config ${GITHUB_WORKSPACE}/.github/pa11y.config \
                  --sitemap https://data-guidelines.scilifelab.se/sitemap.xml \
                  --sitemap-exclude 'https://data-guidelines.scilifelab.se/files'
